name: CI

on: [push]

jobs:
  build:
    name: Testing on ${{ matrix.os }} with Python version ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run linter
        run: mypy ./renderer && flake8 ./renderer